import { TerminalStyle } from '../types/terminal-types';

export const RetroGreen: TerminalStyle = {
    gridColor: '#1a1a1a',
    background: '#0c0c0c',
    border: '#32cd32',
    headerBackground: '#1a1a1a',
    headerBorder: '#32cd32',
    text: '#32cd32',
    headerText: '#32cd32',
    dotColor: '#32cd32',
    inputBackground: '#1a1a1a',
    inputBorder: '#32cd32',
    inputText: '#32cd32',
    inputPlaceholder: '#1f631f',
    buttonBackground: '#32cd32',
    buttonHover: '#1f631f',
    buttonText: '#0c0c0c',
    messageBackground: '#1a1a1a',
    messageText: '#32cd32',
    userMessageBackground: '#1f631f',
    userMessageText: '#ffffff',
    messageBorder: '#32cd32',
    timestampText: '#1f631f',
    resizeHandleBorder: '#32cd32'
};

export const RetroBeige: TerminalStyle = {
    gridColor: '#d6d3c3',
    background: '#e9e6d8',
    border: '#d2cfc0',
    headerBackground: '#e9e6d8',
    headerBorder: '#d2cfc0',
    text: '#5c574a',
    headerText: '#5c574a',
    dotColor: '#5c574a',
    inputBackground: '#f1eee1',
    inputBorder: '#d2cfc0',
    inputText: '#5c574a',
    inputPlaceholder: '#a29e8c',
    buttonBackground: '#e2bd8f',
    buttonHover: '#d3a978',
    buttonText: '#5c574a',
    messageBackground: '#f1eee1',
    messageText: '#5c574a',
    userMessageBackground: '#e2dfcf',
    userMessageText: '#5c574a',
    messageBorder: '#d2cfc0',
    timestampText: '#928e7c',
    resizeHandleBorder: '#d2cfc0'
};

export const CyberpunkNeon: TerminalStyle = {
    gridColor: '#1a1a2e',
    background: '#0a0a1f',
    border: '#ff00ff',
    headerBackground: '#1a1a2e',
    headerBorder: '#ff00ff',
    text: '#00ffff',
    headerText: '#ff00ff',
    dotColor: '#ff00ff',
    inputBackground: '#1a1a2e',
    inputBorder: '#ff00ff',
    inputText: '#00ffff',
    inputPlaceholder: '#6a6a8e',
    buttonBackground: '#ff00ff',
    buttonHover: '#b300b3',
    buttonText: '#ffffff',
    messageBackground: '#1a1a2e',
    messageText: '#00ffff',
    userMessageBackground: '#b300b3',
    userMessageText: '#ffffff',
    messageBorder: '#ff00ff',
    timestampText: '#6a6a8e',
    resizeHandleBorder: '#ff00ff'
};

export const MonochromeMinimal: TerminalStyle = {
    gridColor: '#2a2a2a',
    background: '#000000',
    border: '#ffffff',
    headerBackground: '#1a1a1a',
    headerBorder: '#ffffff',
    text: '#ffffff',
    headerText: '#ffffff',
    dotColor: '#ffffff',
    inputBackground: '#1a1a1a',
    inputBorder: '#ffffff',
    inputText: '#ffffff',
    inputPlaceholder: '#808080',
    buttonBackground: '#ffffff',
    buttonHover: '#808080',
    buttonText: '#000000',
    messageBackground: '#1a1a1a',
    messageText: '#ffffff',
    userMessageBackground: '#333333',
    userMessageText: '#ffffff',
    messageBorder: '#ffffff',
    timestampText: '#808080',
    resizeHandleBorder: '#ffffff'
};

export const OceanBlue: TerminalStyle = {
    gridColor: '#1a2a3a',
    background: '#0a1520',
    border: '#00bfff',
    headerBackground: '#1a2a3a',
    headerBorder: '#00bfff',
    text: '#87ceeb',
    headerText: '#00bfff',
    dotColor: '#00bfff',
    inputBackground: '#1a2a3a',
    inputBorder: '#00bfff',
    inputText: '#87ceeb',
    inputPlaceholder: '#4a5a6a',
    buttonBackground: '#00bfff',
    buttonHover: '#0099cc',
    buttonText: '#ffffff',
    messageBackground: '#1a2a3a',
    messageText: '#87ceeb',
    userMessageBackground: '#0099cc',
    userMessageText: '#ffffff',
    messageBorder: '#00bfff',
    timestampText: '#4a5a6a',
    resizeHandleBorder: '#00bfff'
};
